// src/app/views/base/footer/footer/footer.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { TranslateModule } from '@ngx-translate/core';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [
    CommonModule, TranslateModule
  ],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.css',
  changeDetection: ChangeDetectionStrategy.Default,
})
export class FooterComponent { }

<div class="futre row text-center">
  <div class="col-lg-3">
    <img class="logo-footer" src="assets/res/logos/logo-blanco.png" />
  </div>
  <div class="col-lg-2 text-start site-map">
    <h3>{{"sitio" | translate}}</h3>
    <a href="">{{"inicio"|translate}}</a><br>
    <a href="servicios">{{"servicios"|translate}}</a><br>
    <a href="contacto">{{"contacto"|translate}}</a><br>
    <a href="mi-reserva">{{"mi-reserva"|translate}}</a><br>
    <a href="reservar">{{"reservar"|translate}}</a><br>
    <a href="admin">{{"admin"|translate}}</a>

  </div>
  <div class="col-lg-2 text-start site-map">
    <h3>{{"contacto" | translate}}</h3>
    <a class="d-none d-sm-block" href="https://www.instagram.com/complejo_don_florito/" target="_blank">
      <i class="bi bi-instagram"></i> Instagram
    </a>
    <a class="d-none d-sm-block" href="https://wa.me/56995278783" target="_blank">
      <i class="bi bi-whatsapp"></i> Whatsapp
    </a>
    <a class="d-none d-sm-block" href="mailto:contacto@donflorito.cl">
      <i class="bi bi-envelope"></i> Email
    </a>
    <div class="hstack d-block d-sm-none contacto-movil text-center">
      <a href="https://www.instagram.com/complejo_don_florito/" target="_blank">
        <i class="bi bi-instagram"></i>
      </a>&nbsp;&nbsp;
      <a href="https://wa.me/56995278783" target="_blank">
        <i class="bi bi-whatsapp"></i>
      </a>&nbsp;&nbsp;
      <a href="mailto:contacto@donflorito.cl">
        <i class="bi bi-envelope"></i>
      </a>
      
    </div>
  </div>

  <div class="col-lg-5">
    <img class="logo-webpay" src="assets/res/logos/webpay-blanco.png" />
  </div>
  <hr />
  <p class="thepit-firma"> <a href="https://thepit.cl" target="_blank">ThePit It Development</a> - 2024</p>
</div>

// src/components/layout/footer.tsx
'use client';

import Link from 'next/link';
import { useTranslations } from '@/lib/i18n';

export function AppFooter() {
  const t = useTranslations();

  return (
    <footer className="app-footer mt-auto">
      <div className="container py-4">
        <div className="row text-center text-lg-start align-items-center g-4">
          <div className="col-lg-3">
            <img className="logo-footer" src="/assets/res/logos/logo-blanco.png" alt="Don Florito blanco" />
          </div>
          <div className="col-lg-2 site-map">
            <h3>{t('sitio')}</h3>
            <Link href="/">{t('inicio')}</Link>
            <Link href="/servicios">{t('servicios')}</Link>
            <Link href="/contacto">{t('contacto')}</Link>
            <Link href="/mi-reserva">{t('mi-reserva')}</Link>
            <Link href="/reservar">{t('reservar')}</Link>
            <Link href="/admin">{t('admin')}</Link>
          </div>
          <div className="col-lg-2 site-map">
            <h3>{t('contactoFooter')}</h3>
            <a href="https://www.instagram.com/complejo_don_florito/" target="_blank" rel="noreferrer">
              <i className="bi bi-instagram" /> Instagram
            </a>
            <a href="https://wa.me/56995278783" target="_blank" rel="noreferrer">
              <i className="bi bi-whatsapp" /> Whatsapp
            </a>
            <a href="mailto:contacto@donflorito.cl">
              <i className="bi bi-envelope" /> Email
            </a>
          </div>
          <div className="col-lg-5 text-center text-lg-end">
            <img className="logo-webpay" src="/assets/res/logos/webpay-blanco.png" alt="Webpay" />
          </div>
        </div>
        <hr />
        <p className="thepit-firma text-center mb-0">
          <a href="https://thepit.cl" target="_blank" rel="noreferrer">
            ThePit It Development
          </a>{' '}
          - 2024
        </p>
      </div>
    </footer>
  );
}
